# Generated by Django 4.2.13 on 2026-03-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('category', models.CharField(choices=[('GENERAL', 'Thông báo chung'), ('MAINTENANCE', 'Bảo trì'), ('RULE', 'Nội quy'), ('EVENT', 'Sự kiện'), ('SECURITY', 'An ninh'), ('FEE', 'Phí & thanh toán'), ('EMERGENCY', 'Khẩn cấp')], default='GENERAL', max_length=15)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Ghim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/files/%Y/%m/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'db_table': 'announcements_announcement',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
