# Generated by Django 4.2.13 on 2026-03-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='Số CCCD/CMND')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True)),
                ('hometown', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quê quán')),
                ('permanent_address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ thường trú')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='residents/%Y/%m/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Người liên hệ khẩn cấp')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cư dân',
                'db_table': 'residents_resident',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('rent_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tiền thuê (VNĐ/tháng)')),
                ('deposit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền đặt cọc')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hiệu lực'), ('EXPIRED', 'Đã hết hạn'), ('CANCELLED', 'Đã hủy'), ('PENDING', 'Chờ duyệt')], default='PENDING', max_length=20)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='File hợp đồng')),
                ('note', models.TextField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='buildings.apartment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'db_table': 'residents_contract',
                'ordering': ['-start_date'],
            },
        ),
    ]
