# Generated by Django 4.2.13 on 2026-03-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slot_number', models.CharField(max_length=20, unique=True)),
                ('slot_type', models.CharField(choices=[('CAR', 'Ô tô'), ('MOTORBIKE', 'Xe máy'), ('BICYCLE', 'Xe đạp')], max_length=15)),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tầng hầm/bãi')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('OCCUPIED', 'Đang dùng')], default='AVAILABLE', max_length=10)),
                ('monthly_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chỗ đậu xe',
                'db_table': 'vehicles_parkingslot',
                'ordering': ['slot_number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Ô tô'), ('MOTORBIKE', 'Xe máy'), ('BICYCLE', 'Xe đạp'), ('OTHER', 'Khác')], max_length=15)),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Biển số xe')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hãng xe')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mẫu xe')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu sắc')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số thẻ xe')),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/%Y/%m/')),
                ('note', models.TextField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='buildings.apartment')),
                ('parking_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.parkingslot')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Phương tiện',
                'db_table': 'vehicles_vehicle',
                'ordering': ['license_plate'],
            },
        ),
    ]
