# Generated by Django 4.2.13 on 2026-03-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('ELECTRIC', 'Điện'), ('PLUMBING', 'Nước / Ống dẫn'), ('HVAC', 'Điều hòa / Thông gió'), ('ELEVATOR', 'Thang máy'), ('SECURITY', 'An ninh / Khóa cửa'), ('PAINTING', 'Sơn tường'), ('FLOOR', 'Sàn nhà'), ('OTHER', 'Khác')], max_length=20)),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('ASSIGNED', 'Đã phân công'), ('IN_PROCESS', 'Đang xử lý'), ('RESOLVED', 'Đã giải quyết'), ('CLOSED', 'Đã đóng'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='buildings.apartment')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Yêu cầu bảo trì',
                'db_table': 'maintenance_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
