# Generated by Django 4.2.13 on 2026-03-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên tòa nhà')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings/%Y/%m/')),
                ('built_year', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_buildings', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý')),
            ],
            options={
                'verbose_name': 'Tòa nhà',
                'db_table': 'buildings_building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('floor_number', models.PositiveIntegerField(verbose_name='Số tầng')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Tầng',
                'db_table': 'buildings_floor',
                'ordering': ['floor_number'],
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('apartment_number', models.CharField(max_length=20, verbose_name='Số căn hộ')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Diện tích (m²)')),
                ('bedroom_count', models.PositiveSmallIntegerField(default=1)),
                ('bathroom_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('OCCUPIED', 'Đang ở'), ('MAINTENANCE', 'Đang bảo trì'), ('RESERVED', 'Đã đặt cọc')], default='AVAILABLE', max_length=20)),
                ('rent_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá thuê (VNĐ/tháng)')),
                ('direction', models.CharField(blank=True, choices=[('N', 'Bắc'), ('S', 'Nam'), ('E', 'Đông'), ('W', 'Tây'), ('NE', 'Đông Bắc'), ('NW', 'Tây Bắc'), ('SE', 'Đông Nam'), ('SW', 'Tây Nam')], max_length=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apartments/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('balcony', models.BooleanField(default=False)),
                ('furniture_included', models.BooleanField(default=False, verbose_name='Có nội thất')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.floor')),
            ],
            options={
                'verbose_name': 'Căn hộ',
                'db_table': 'buildings_apartment',
                'ordering': ['floor__floor_number', 'apartment_number'],
                'unique_together': {('floor', 'apartment_number')},
            },
        ),
    ]
