# Generated by Django 4.2.13 on 2026-03-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên loại phí')),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('MONTH', 'Tháng'), ('M2', 'm²'), ('VEHICLE', 'Xe'), ('USAGE', 'Lần dùng'), ('FIXED', 'Cố định')], default='MONTH', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá (VNĐ)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Bắt buộc')),
                ('apply_to_all', models.BooleanField(default=True, verbose_name='Áp dụng tất cả căn hộ')),
            ],
            options={
                'verbose_name': 'Loại phí',
                'db_table': 'fees_feetype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Năm')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('due_date', models.DateField(verbose_name='Hạn thanh toán')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('OVERDUE', 'Quá hạn'), ('CANCELLED', 'Đã hủy'), ('PARTIAL', 'Thanh toán một phần')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='buildings.apartment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fees.feetype')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'db_table': 'fees_invoice',
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('fee_type', 'apartment', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền đã trả')),
                ('paid_at', models.DateTimeField(verbose_name='Thời gian thanh toán')),
                ('method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('TRANSFER', 'Chuyển khoản'), ('MOMO', 'MoMo'), ('VNPAY', 'VNPay'), ('OTHER', 'Khác')], default='CASH', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch')),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.invoice')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'db_table': 'fees_payment',
                'ordering': ['-paid_at'],
            },
        ),
    ]
