# Generated by Django 4.2.13 on 2026-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='unit',
            field=models.CharField(choices=[('MONTH', 'Tháng'), ('M2', 'm²'), ('VEHICLE', 'Xe'), ('KWH', 'kWh'), ('M3', 'm³'), ('USAGE', 'Lần dùng'), ('FIXED', 'Cố định')], default='MONTH', max_length=10),
        ),
    ]
