# Generated by Django 4.2.13 on 2026-03-15 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên khách')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CCCD')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('purpose', models.CharField(max_length=300, verbose_name='Mục đích thăm')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visitors', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='residents.resident')),
                ('visit_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='buildings.apartment')),
            ],
            options={
                'verbose_name': 'Khách thăm',
                'db_table': 'visitors_visitor',
                'ordering': ['-check_in'],
            },
        ),
    ]
